config.json <- system.file('extdata', 'config.json', package='configr')
config.yml <- system.file('extdata', 'config.yml', package='configr')
config.ini <- system.file('extdata', 'config.ini', package='configr')
flog.info(sprintf("Debug:%s config file type:%s", config.json, get.config.type(config.json)))
flog.info("Debug:read.config(config.json)")
print(read.config(config.json))
flog.info("Debug:read.config(config.yml)")
print(read.config(config.yml))
flog.info("Debug:read.config(config.ini)")
print(read.config(config.ini))

flog.info("Debug:eval.config(file=config.json)")
print(eval.config(file = config.json))
flog.info("Debug:eval.config(file=config.yml)")
print(eval.config(file = config.yml))
flog.info("Debug:eval.config(file=config.ini)")
print(eval.config(file = config.ini))

flog.info("Debug:eval.config.groups(file=config.json)")
print(eval.config.groups(file = config.json))
flog.info("Debug:eval.config.groups(file=config.yml)")
print(eval.config.groups(file = config.yml))
flog.info("Debug:eval.config.groups(file=config.ini)")
print(eval.config.groups(file = config.ini))
