config.json <- system.file('extdata', 'config.json', package='configr')
config.yaml <- system.file('extdata', 'config.yaml', package='configr')
config.ini <- system.file('extdata', 'config.ini', package='configr')
config.toml <- system.file('extdata', 'config.toml', package='configr')
config.error.toml <- system.file('extdata', 'config.error.toml', package='configr')
print("Debug:read.config(config.json)")
print(read.config(config.json))
print("Debug:read.config(config.yaml)")
print(read.config(config.yaml))
print("Debug:read.config(config.ini)")
print(read.config(config.ini))
print("Debug:read.config(config.toml)")
print(read.config(config.toml))

print("Debug:eval.config(file=config.json)")
print(eval.config(file = config.json))
print("Debug:eval.config(file=config.yaml)")
print(eval.config(file = config.yaml))
print("Debug:eval.config(file=config.ini)")
print(eval.config(file = config.ini))
print("Debug:eval.config(file=config.toml)")
print(eval.config(file = config.toml))

print("Debug:eval.config.groups(file=config.json)")
print(eval.config.groups(file = config.json))
print("Debug:eval.config.groups(file=config.yaml)")
print(eval.config.groups(file = config.yaml))
print("Debug:eval.config.groups(file=config.ini)")
print(eval.config.groups(file = config.ini))
print("Debug:eval.config.groups(file=config.toml)")
print(eval.config.groups(file = config.toml))

# Test process fail format file
print("Debug:read.config(file='unknow')")
print(suppressWarnings(read.config(file = 'unknow')))
print("Debug:read.config(file=config.error.toml)")
print(suppressWarnings(read.config(file = config.error.toml)))

print("Debug:eval.config.groups(file='unknow')")
print(suppressWarnings(eval.config.groups(file = 'unknow')))
print("Debug:eval.config.groups(file=config.error.toml)")
print(suppressWarnings(eval.config.groups(file = config.error.toml)))

print("Debug:eval.config(file='unknow')")
print(suppressWarnings(eval.config(file = 'unknow')))
print("Debug:eval.config(file=config.error.toml)")
print(suppressWarnings(eval.config(file = config.error.toml)))

